# Generated by Django 5.2.8 on 2025-12-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_receipt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='date',
        ),
    ]
